#! /bin/bash
_run_tests_ () {
    for f in build/test_*; do
        ./${f}
    done
}

_check_compiler_ () {
    CComp=$1
    CFlags=$2
    make clean && \
        CC=${CComp} CFLAGS=${CFlags} make ahre && \
        CC=${CComp} CFLAGS=${CFlags} make test_all && \
        _run_tests_
}

#_check_compiler_ tcc -DAHRE_REGEX_DISABLED && \ TODO: fix tcc build
    _check_compiler_ clang && \
    _check_compiler_ gcc && \
    make clean
