#! /bin/bash
_run_tests_ () {
    for f in build/test_*; do
        ./${f}
    done
}

_check_compiler_ () {
    CComp=$1
    CFlags=$2
    make clean && \
        CC=${CComp} CFLAGS=${CFlags} make && \
        CC=${CComp} CFLAGS=${CFlags} make test_all && \
        _run_tests_
}

_check_compiler_ tcc -DNO_REGEX && \
    _check_compiler_ clang && \
    _check_compiler_ gcc
