name: C CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: libcurl
      run: sudo apt update && sudo apt install -y libcurl4-openssl-dev
    - name: lexbor-clone
      run: git clone https://github.com/lexbor/lexbor 
    - name: lexbor-install
          cd lexbor && cmake . && make && sudo make install
    - name: hashi
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: make tests
      run: make run_tests
   
