name: C CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: hashi
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: make tests
      run: make run_tests
   
