name: C CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: libcurl
      run: sudo apt update && sudo apt install -y libcurl4-openssl-dev
    - name: lexbor
      run: curl -O https://lexbor.com/keys/lexbor_signing.key && sudo apt-key add lexbor_signing.key && sudo apt update && sudo apt install liblexbor && sudo apt install liblexbor-dev
    - name: hashi
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: make tests
      run: make run_tests
   
