name: C CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: update-apt
      run: sudo apt update
    - name: install-gcc
      run: sudo apt install -y gcc 
    - name: libcurl
      run: sudo apt install -y libcurl4-openssl-dev
    - name: lexbor-clone
      run: git clone https://github.com/lexbor/lexbor 
    - name: lexbor-install
      run: cd lexbor && cmake . && make && sudo make install
    - name: hashi
      run: git submodule update --init --recursive
    - name: create-build-dir
      run: mkdir build
    - name: make
      run: make
